models/Causa.py
from utils.db import db


#Clase causa, sus atributos y los tipos de estos ultimos
class Causa (db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fechaini = db.Column(db.DateTime)
    ptvo= db.Column(db.Integer)
    nroExpte = db.Column(db.Integer)
    detalle = db.Column(db.String(100))
    secretario = db.Column(db.Integer)
    instructor = db.Column(db.Integer)



#constructor
    def __init__(self, fechaini, ptvo, nroExpte, detalle, secretario, instructor):
        self.fechaini = fechaini
        self.ptvo = ptvo
        self.nroExpte = nroExpte
        self.detalle = detalle
        self.secretario = secretario
        self.instructor = instructor
   

models/NroJ.py
from utils.db import db


#Clase efectivo, sus atributos y los tipos de estos ultimos
class nroJ (db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fecha = db.Column(db.DateTime)
    secretario = db.Column(db.Integer)
    destino = db.Column(db.String(100))
    motivo = db.Column(db.String(100))

    

#constructor
    def __init__(self, fecha, secretario, destino, motivo):
        self.fecha = fecha
        self.secretario = secretario
        self.destino = destino
        self.motivo = motivo

models/expte.py
from utils.db import db


#Clase expte, sus atributos y los tipos de estos ultimos
class Expte (db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fechaing = db.Column(db.DateTime)
    proc = db.Column(db.String(100))
    detalle = db.Column(db.String(100))
    secretario = db.Column(db.Integer)
    instructor = db.Column(db.Integer)
    destino = db.Column(db.String(100))
    fechasal = db.Column(db.DateTime)
    obs = db.Column(db.String(100))

#constructor
    def __init__(self, fechaing, proc, detalle, secretario, instructor, destino, fechasal, obs):
        self.fechaing = fechaing
        self.proc = proc
        self.detalle = detalle
        self.secretario = secretario
        self.instructor = instructor
        self.destino = destino
        self.fechasal = fechasal
        self.obs = obs        

routes/Causas.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, send_file
from models.Causa import Causa
from models.efectivo import Efectivo
from models.expte import Expte
from utils import db
from utils.db import db
from datetime import datetime
import pandas as pd
from io import BytesIO
from flask_login import login_required

#Uso de blueprint, sirve para no tener que importar app y cargar los metodos y los html aca
causas = Blueprint('causas', __name__)

@causas.route('/causas')
@login_required
def home():
    causas = Causa.query.all()
    return render_template('Causas.html', causas=causas)


@causas.route('/new_causa', methods=['POST'])
def add_causa():
    fechaini=datetime.strptime(request.form['fechaini'], '%Y-%m-%d')
    ptvo=request.form['ptvo']
    nroExpte=request.form['nroExpte']
    detalle=request.form['detalle']
    secretario=request.form['secretario']
    instructor=request.form['instructor']


    

    new_causa = Causa(fechaini, ptvo, nroExpte, detalle, secretario, instructor,)
    
    db.session.add(new_causa)
    db.session.commit()


    flash("Se ha añadido una causa satisfactoriamente!")

    return redirect(url_for('causas.home'))

@causas.route('/causas/update/<id>', methods=['POST', 'GET'])
def update(id):
        print(id)
        causa = Causa.query.get(id)
        if request.method == 'POST':
            
            causa.fechaini = request.form["fechaini"]
            causa.ptvo = request.form["ptvo"]
            causa.nroExpte = request.form["nroExpte"]
            causa.detalle = request.form["detalle"]
            causa.secretario = request.form["secretario"]
            causa.instructor = request.form["instructor"]



            db.session.commit()
            
            flash("Se actualizó una causa satisfactoriamente!")

            return redirect(url_for('causas.home')) 
        
        
        return render_template('updateCausas.html', causa=causa)

@causas.route('/causas/delete/<id>')
def delete(id):
        causa = Causa.query.get(id)
        db.session.delete(causa)
        db.session.commit()

        flash("Se borró una causa satisfactoriamente!")


        return redirect(url_for('causas.home'))

@causas.route('/export/causas')
def export_excel():
    # Consulta de los datos de la base de datos
    causas = Causa.query.all()
    
    # Crear un DataFrame de Pandas
    data = [
        {
            "ID": causa.id,
            "Fecha Inicio": causa.fechaini,
            "Of Preventivo": causa.ptvo,
            "Nro. Expte": causa.nroExpte,
            "Detalle": causa.detalle,
            "Secretario": causa.secretario,
            "Instructor": causa.instructor
        }
        for causa in causas
    ]
    df = pd.DataFrame(data)

    # Guardar el DataFrame en un archivo Excel en memoria
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name="causas")
    output.seek(0)

    # Enviar el archivo al cliente para descargarlo
    return send_file(output, as_attachment=True, download_name="causas.xlsx", mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")

@causas.route('/buscar', methods=['GET'])
def buscar():
    query = request.args.get('query')
    tabla = request.args.get('tabla')
    resultados = []

    if query:
        if tabla == 'efectivo':
            resultados = Efectivo.query.filter(
                (Efectivo.fullname.like(f'%{query}%')) |
                (Efectivo.DNI.like(f'%{query}%')) |
                (Efectivo.LP.like(f'%{query}%'))
            ).all()

        elif tabla == 'expediente':
            resultados = Expte.query.filter(
                (Expte.proc.like(f'%{query}%')) |
                (Expte.detalle.like(f'%{query}%')) |
                (Expte.secretario.like(f'%{query}%')) |
                (Expte.instructor.like(f'%{query}%'))
            ).all()

        elif tabla == 'causa':
            resultados = Causa.query.filter(
                (Causa.ptvo.like(f'%{query}%')) |
                (Causa.detalle.like(f'%{query}%')) |
                (Causa.nroExpte.like(f'%{query}%')) |
                (Causa.secretario.like(f'%{query}%')) |
                (Causa.instructor.like(f'%{query}%'))
            ).all()

        elif tabla == 'todos':
            resultados_efectivo = Efectivo.query.filter(
                (Efectivo.fullname.like(f'%{query}%')) |
                (Efectivo.DNI.like(f'%{query}%')) |
                (Efectivo.LP.like(f'%{query}%'))
            ).all()

            resultados_expediente = Expte.query.filter(
                (Expte.proc.like(f'%{query}%')) |
                (Expte.detalle.like(f'%{query}%')) |
                (Expte.secretario.like(f'%{query}%')) |
                (Expte.instructor.like(f'%{query}%'))
            ).all()

            resultados_causa = Causa.query.filter(
                (Causa.ptvo.like(f'%{query}%')) |
                (Causa.detalle.like(f'%{query}%')) |
                (Causa.nroExpte.like(f'%{query}%')) |
                (Causa.secretario.like(f'%{query}%')) |
                (Causa.instructor.like(f'%{query}%'))
            ).all()

            resultados = resultados_efectivo + resultados_expediente + resultados_causa

    return render_template('resultados.html', resultados=resultados)


@causas.route('/about')
def about():
    return render_template('about.html')

routes/exptes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, send_file
from models.expte import Expte
from models.Causa import Causa
from models.efectivo import Efectivo
from utils import db
from utils.db import db
from datetime import datetime
import pandas as pd
from io import BytesIO
from flask_login import login_required

#Uso de blueprint, sirve para no tener que importar app y cargar los metodos y los html aca
exptes = Blueprint('exptes', __name__)

@exptes.route('/exptes')
@login_required
def home():
    exptes = Expte.query.all()
    return render_template('expedientes.html', exptes=exptes)


@exptes.route('/new_expte', methods=['POST'])
def add_expte():
    fechaing=datetime.strptime(request.form['fechaing'], '%Y-%m-%d')
    proc=request.form['proc']
    detalle=request.form['detalle']
    secretario=request.form['secretario']
    instructor=request.form['instructor']
    destino=request.form['destino']
    fechasal=request.form['fechasal']
    if fechasal:
        fechasal = datetime.strptime(fechasal, '%Y-%m-%d')
    else:
        fechasal = None
    obs=request.form['obs']
    

    new_expte = Expte(fechaing, proc, detalle, secretario, instructor, destino, fechasal, obs)
    
    db.session.add(new_expte)
    db.session.commit()


    flash("Se ha añadido un expediente satisfactoriamente!")

    return redirect(url_for('exptes.home'))

@exptes.route('/exptes/update/<id>', methods=['POST', 'GET'])
def update(id):
        print(id)
        expte = Expte.query.get(id)
        if request.method == 'POST':
            
            expte.fechaing = request.form["fechaing"]
            expte.proc = request.form["proc"]
            expte.detalle = request.form["detalle"]
            expte.secretario = request.form["secretario"]
            expte.instructor = request.form["instructor"]
            expte.destino = request.form["destino"]
            expte.fechasal = request.form["fechasal"]
            expte.obs = request.form["obs"]

            db.session.commit()
            
            flash("Se actualizó un expediente satisfactoriamente!")

            return redirect(url_for('exptes.home')) 
        
        
        return render_template('updateexpte.html', expte=expte)

@exptes.route('/exptes/delete/<id>')
def delete(id):
        expte = Expte.query.get(id)
        db.session.delete(expte)
        db.session.commit()

        flash("Se borró un expediente satisfactoriamente!")


        return redirect(url_for('exptes.home'))

@exptes.route('/export/exptes')
def export_excel():
    # Consulta de los datos de la base de datos
    exptes = Expte.query.all()
    
    # Crear un DataFrame de Pandas
    data = [
        {
            "ID": expte.id,
            "Fecha Ingreso": expte.fechaing,
            "Procedencia": expte.proc,
            "Detalle": expte.detalle,
            "Secretario": expte.secretario,
            "Instructor": expte.instructor,
            "Destino": expte.destino,
            "Fecha Salida": expte.fechasal,
            "Observaciones": expte.obs,

        }
        for expte in exptes
    ]
    df = pd.DataFrame(data)

    # Guardar el DataFrame en un archivo Excel en memoria
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name="exptes")
    output.seek(0)

    # Enviar el archivo al cliente para descargarlo
    return send_file(output, as_attachment=True, download_name="exptes.xlsx", mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")

@exptes.route('/buscar', methods=['GET'])
def buscar():
    query = request.args.get('query')
    tabla = request.args.get('tabla')
    resultados = []

    if query:
        if tabla == 'efectivo':
            resultados = Efectivo.query.filter(
                (Efectivo.fullname.like(f'%{query}%')) |
                (Efectivo.DNI.like(f'%{query}%')) |
                (Efectivo.LP.like(f'%{query}%'))
            ).all()

        elif tabla == 'expediente':
            resultados = Expte.query.filter(
                (Expte.proc.like(f'%{query}%')) |
                (Expte.detalle.like(f'%{query}%')) |
                (Expte.secretario.like(f'%{query}%')) |
                (Expte.instructor.like(f'%{query}%'))
            ).all()

        elif tabla == 'causa':
            resultados = Causa.query.filter(
                (Causa.ptvo.like(f'%{query}%')) |
                (Causa.detalle.like(f'%{query}%')) |
                (Causa.nroExpte.like(f'%{query}%')) |
                (Causa.secretario.like(f'%{query}%')) |
                (Causa.instructor.like(f'%{query}%'))
            ).all()

        elif tabla == 'todos':
            resultados_efectivo = Efectivo.query.filter(
                (Efectivo.fullname.like(f'%{query}%')) |
                (Efectivo.DNI.like(f'%{query}%')) |
                (Efectivo.LP.like(f'%{query}%'))
            ).all()

            resultados_expediente = Expte.query.filter(
                (Expte.proc.like(f'%{query}%')) |
                (Expte.detalle.like(f'%{query}%')) |
                (Expte.secretario.like(f'%{query}%')) |
                (Expte.instructor.like(f'%{query}%'))
            ).all()

            resultados_causa = Causa.query.filter(
                (Causa.ptvo.like(f'%{query}%')) |
                (Causa.detalle.like(f'%{query}%')) |
                (Causa.nroExpte.like(f'%{query}%')) |
                (Causa.secretario.like(f'%{query}%')) |
                (Causa.instructor.like(f'%{query}%'))
            ).all()

            resultados = resultados_efectivo + resultados_expediente + resultados_causa

    return render_template('resultados.html', resultados=resultados)


@exptes.route('/about')
def about():
    return render_template('about.html')

routes/users.py
from flask import Blueprint, request, redirect, url_for, render_template, flash, session
from models.User import User
from flask_login import login_user, login_required, logout_user, current_user
from utils import db
from utils.db import db

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        if User.query.filter_by(username=username).first():
            flash('El nombre de usuario ya existe.')
            return redirect(url_for('users.register'))
        
        new_user = User(username=username)
        new_user.set_password(password)
        db.session.add(new_user)
        db.session.commit()
        flash('Usuario registrado con éxito.')
        return redirect(url_for('users.login'))
    return render_template('register.html')

@users.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(username=username).first()
        if user and user.check_password(password):
            login_user(user)
            flash('Inicio de sesión exitoso.')
            return redirect(url_for('efectivos.home'))
        else:
            flash('Usuario o contraseña incorrectos.')
    return render_template('login.html')

@users.route('/logout')
def logout():
    logout_user()
    flash('Sesión cerrada.')
    return redirect(url_for('users.login'))

templates/partials/_CausaForm.html
<form action="/new_causa" method="POST" class="card bg-black text-light">
    <div class="card-body p-4">
      <h1 class="h5 mb-4">Añadir Causa</h1>
  
      <div class="mb-3">
        <label for="fechaini">Fecha de Inicio:</label>
        <input
          type="date"
          id="fechaini"
          name="fechaini"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Fecha Inicio"
          required
        />
      </div>

      <div class="mb-3">
        <label for="ptvo">Nro. Preventivo:</label>
        <input
          type="text"
          id="ptvo"
          name="ptvo"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Nro Preventivo"
          required
        />
      </div>
      
      <div class="mb-3">
        <label for="nroExpte">Nro. Expediente:</label>
        <input
          type="text"
          id="nroExpte"
          name="nroExpte"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Nro. Expediente"
          
        />
      </div>
  
      <div class="mb-3">
        <label for="detalle">Detalle:</label>
        <input
          type="text"
          id="detalle"
          name="detalle"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Detalle"
          required
        />
      </div>
  
      <div class="mb-3">
        <label for="secretario">Secretario (ID):</label>
        <input
          type="number"
          id="secretario"
          name="secretario"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="ID del secretario"
          required
        />
      </div>
  
      <div class="mb-3">
        <label for="instructor">Instructor (ID):</label>
        <input
          type="number"
          id="instructor"
          name="instructor"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="ID del instructor"
          required
        />
      </div>


  
      <button type="submit" class="btn btn-primary">Guardar Causa</button>
      
      <a href="/export/causas" class="btn btn-light text-dark rounded-1 mx-2">Imprimir causas</a>

    </div>
  </form>

templates/partials/_NroJForm.html
<form action="/new_NroJ" method="POST" class="card bg-black text-light">
    <div class="card-body p-4">
      <h1 class="h5 mb-4">Marcar Numero Judicial</h1>
  
      <div class="mb-3">
        <label for="fecha">Fecha:</label>
        <input
          type="date"
          id="fecha"
          name="fecha"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Fecha"
          required
        />
      </div>

  
      <div class="mb-3">
        <label for="secretario">Secretario (ID):</label>
        <input
          type="number"
          id="secretario"
          name="secretario"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="ID del secretario"
          required
        />
      </div>
  

      <div class="mb-3">
        <label for="destino">Destino:</label>
        <input
          type="text"
          id="destino"
          name="destino"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Destino"
          
        />
      </div>


      <div class="mb-3">
        <label for="motivo">Motivo:</label>
        <input
          type="text"
          id="motivo"
          name="motivo"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Motivo"
          
        />
      </div>
  
      <button type="submit" class="btn btn-primary">Guardar Numero</button>
      <a href="/export/NrosJ" class="btn btn-light text-dark rounded-1 mx-2">Imprimir Numeros</a>
    </div>
  </form>

templates/partials/_NroVarioForm.html
<form action="/new_NroV" method="POST" class="card bg-black text-light">
    <div class="card-body p-4">
      <h1 class="h5 mb-4">Marcar Numero Vario</h1>
  
      <div class="mb-3">
        <label for="fecha">Fecha:</label>
        <input
          type="date"
          id="fecha"
          name="fecha"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Fecha"
          required
        />
      </div>

  
      <div class="mb-3">
        <label for="secretario">Secretario (ID):</label>
        <input
          type="number"
          id="secretario"
          name="secretario"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="ID del secretario"
          required
        />
      </div>
  

      <div class="mb-3">
        <label for="destino">Destino:</label>
        <input
          type="text"
          id="destino"
          name="destino"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Destino"
          
        />
      </div>


      <div class="mb-3">
        <label for="motivo">Motivo:</label>
        <input
          type="text"
          id="motivo"
          name="motivo"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Motivo"
          
        />
      </div>
  
      <button type="submit" class="btn btn-primary">Guardar Numero</button>
      <a href="/export/NrosV" class="btn btn-light text-dark rounded-1 mx-2">Imprimir Numeros</a>
    </div>
  </form>

templates/partials/_SecuForm.html
<form action="/new_secuestro" method="POST" class="card bg-black text-light">
    <div class="card-body p-4">
      <h1 class="h5 mb-4">Añadir secuestro</h1>
  
      <div class="mb-3">
        <label for="fechaing">Fecha de Ingreso:</label>
        <input
          type="date"
          id="fechaing"
          name="fechaing"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Fecha de Ingreso"
          required
        />
      </div>

      <div class="mb-3">
        <label for="detalle">Detalle:</label>
        <input
          type="text"
          id="detalle"
          name="detalle"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Detalle"
          required
        />
      </div>

      <div class="mb-3">
        <label for="nroExpte">Nro. Expediente:</label>
        <input
          type="text"
          id="nroExpte"
          name="nroExpte"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Nro. Expediente"
          
        />
      </div>
  
      <div class="mb-3">
        <label for="fechasal">Fecha de Salida:</label>
        <input
          type="number"
          id="fechasal"
          name="fechasal"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Fecha de Salida"
          required
        />
      </div>


  
      <button type="submit" class="btn btn-primary">Guardar secuestro</button>
      <a href="/export/secuestros" class="btn btn-light text-dark rounded-1">Imprimir Secuestros</a>
    </div>
  </form>

templates/partials/_expteForm.html
<form action="/new_expte" method="POST" class="card bg-black text-light">
    <div class="card-body p-4">
      <h1 class="h5 mb-4">Añadir expediente</h1>
  
      <div class="mb-3">
        <label for="fechaing">Fecha de Ingreso:</label>
        <input
          type="date"
          id="fechaing"
          name="fechaing"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Fecha Ingreso"
          required
        />
      </div>

      <div class="mb-3">
        <label for="proc">Procedencia:</label>
        <input
          type="text"
          id="proc"
          name="proc"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Procedencia"
          required
        />
      </div>
  
      <div class="mb-3">
        <label for="detalle">Detalle:</label>
        <input
          type="text"
          id="detalle"
          name="detalle"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Detalle"
          required
        />
      </div>
  
      <div class="mb-3">
        <label for="secretario">Secretario (ID):</label>
        <input
          type="number"
          id="secretario"
          name="secretario"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="ID del secretario"
          required
        />
      </div>
  
      <div class="mb-3">
        <label for="instructor">Instructor (ID):</label>
        <input
          type="number"
          id="instructor"
          name="instructor"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="ID del instructor"
          required
        />
      </div>

      <div class="mb-3">
        <label for="destino">Destino:</label>
        <input
          type="text"
          id="destino"
          name="destino"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Destino"
          
        />
      </div>

      <div class="mb-3">
        <label for="fechasal">Fecha de Salida:</label>
        <input
          type="date"
          id="fechasal"
          name="fechasal"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Fecha de Salida"
          
        />
      </div>

      <div class="mb-3">
        <label for="obs">Observaciones:</label>
        <input
          type="text"
          id="obs"
          name="obs"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Observaciones"
          
        />
      </div>
  
      <button type="submit" class="btn btn-primary">Guardar Expediente</button>
      <a href="/export/exptes" class="btn btn-light btn-sm text-dark rounded-1">Imprimir Expedientes</a>
    </div>
  </form>

templates/partials/_message.html
{% with messages = get_flashed_messages() %} {% if messages %} {% for message in
    messages %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      {{message}}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% endfor %} {% endif %} {% endwith %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <img src="{{ url_for('static', filename='images/regpol (1).png') }}" style="height: 70px; " class="img-fluid">
      <a class="navbar-brand" href="/"> <img src="{{ url_for('static', filename='images/nome.png') }}" style="height: 50px;" class="img-fluid"></a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          {% if current_user.is_authenticated %}
            <!-- Mostrar enlaces accesibles solo para usuarios logueados -->
            <li class="nav-item"><a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
          {% else %}
            <!-- Mostrar solo el enlace de login/registro -->
            <li class="nav-item"><a class="nav-link" href="{{ url_for('users.login') }}">Login</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('users.register') }}">Register</a></li>
          {% endif %}

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/secuestros">Secuestros</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/NrosV">Numeros Varios</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/NrosJ">Numeros Judiciales</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/causas">Causas Judiciales</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/exptes">expedientes</a>
          </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Personal</a>
            </li>
        </ul>          
      </div>
    </div>
  </nav>

templates/partials/_taskForm.html
<form action="/new_efectivo" method="POST" class="card bg-black text-light">
    <div class="card-body p-4">
      <h1 class="h5 mb-4">Añadir efectivo</h1>
  
      <div class="mb-3">
        <label for="fullname">Nombre completo:</label>
        <input
          type="text"
          name="fullname"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Nombre completo"
          autofocus
        />
      </div>
  
      <div class="mb-3">
        <label for="jerarquia">Jerarquia:</label>
        <input
          type="text"
          name="jerarquia"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Jerarquia"
          required
        />
      </div>
  
      <div class="mb-3">
        <label for="LP">Legajo:</label>
        <input
          type="number"
          name="LP"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Numero de legajo"
        />
      </div>

      <div class="mb-3">
        <label for="DNI">DNI N°:</label>
        <input
          type="number"
          name="DNI"
          class="form-control rounded-0 bg-dark border-0 text-white"
          placeholder="Numero de DNI"
        />
      </div>
  
      <button class="btn btn-primary mx-4">Guardar</button>

      <!--Actualmente este boton es un poco mas chico que el boton  de Guardar. Necesito hacerlo un poco mas grande -->
      <a href="/export/efectivos" class="btn btn-light text-dark rounded-1 mx-2">Imprimir efectivos</a>
 
    </div>
  </form>