models/Causa.py
from utils.db import db


#Clase causa, sus atributos y los tipos de estos ultimos
class Causa (db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fechaini = db.Column(db.DateTime)
    ptvo= db.Column(db.Integer)
    nroExpte = db.Column(db.Integer)
    detalle = db.Column(db.String(100))
    secretario = db.Column(db.Integer)
    instructor = db.Column(db.Integer)



#constructor
    def __init__(self, fechaini, ptvo, nroExpte, detalle, secretario, instructor):
        self.fechaini = fechaini
        self.ptvo = ptvo
        self.nroExpte = nroExpte
        self.detalle = detalle
        self.secretario = secretario
        self.instructor = instructor
   

routes/Causas.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, send_file
from models.Causa import Causa
from models.efectivo import Efectivo
from models.expte import Expte
from utils import db
from utils.db import db
from datetime import datetime
import pandas as pd
from io import BytesIO
from flask_login import login_required

#Uso de blueprint, sirve para no tener que importar app y cargar los metodos y los html aca
causas = Blueprint('causas', __name__)

@causas.route('/causas')
@login_required
def home():
    causas = Causa.query.all()
    return render_template('Causas.html', causas=causas)


@causas.route('/new_causa', methods=['POST'])
def add_causa():
    fechaini=datetime.strptime(request.form['fechaini'], '%Y-%m-%d')
    ptvo=request.form['ptvo']
    nroExpte=request.form['nroExpte']
    detalle=request.form['detalle']
    secretario=request.form['secretario']
    instructor=request.form['instructor']


    

    new_causa = Causa(fechaini, ptvo, nroExpte, detalle, secretario, instructor,)
    
    db.session.add(new_causa)
    db.session.commit()


    flash("Se ha añadido una causa satisfactoriamente!")

    return redirect(url_for('causas.home'))

@causas.route('/causas/update/<id>', methods=['POST', 'GET'])
def update(id):
        print(id)
        causa = Causa.query.get(id)
        if request.method == 'POST':
            
            causa.fechaini = request.form["fechaini"]
            causa.ptvo = request.form["ptvo"]
            causa.nroExpte = request.form["nroExpte"]
            causa.detalle = request.form["detalle"]
            causa.secretario = request.form["secretario"]
            causa.instructor = request.form["instructor"]



            db.session.commit()
            
            flash("Se actualizó una causa satisfactoriamente!")

            return redirect(url_for('causas.home')) 
        
        
        return render_template('updateCausas.html', causa=causa)

@causas.route('/causas/delete/<id>')
def delete(id):
        causa = Causa.query.get(id)
        db.session.delete(causa)
        db.session.commit()

        flash("Se borró una causa satisfactoriamente!")


        return redirect(url_for('causas.home'))

@causas.route('/export/causas')
def export_excel():
    # Consulta de los datos de la base de datos
    causas = Causa.query.all()
    
    # Crear un DataFrame de Pandas
    data = [
        {
            "ID": causa.id,
            "Fecha Inicio": causa.fechaini,
            "Of Preventivo": causa.ptvo,
            "Nro. Expte": causa.nroExpte,
            "Detalle": causa.detalle,
            "Secretario": causa.secretario,
            "Instructor": causa.instructor
        }
        for causa in causas
    ]
    df = pd.DataFrame(data)

    # Guardar el DataFrame en un archivo Excel en memoria
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name="causas")
    output.seek(0)

    # Enviar el archivo al cliente para descargarlo
    return send_file(output, as_attachment=True, download_name="causas.xlsx", mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")

@causas.route('/buscar', methods=['GET'])
def buscar():
    query = request.args.get('query')
    tabla = request.args.get('tabla')
    resultados = []

    if query:
        if tabla == 'efectivo':
            resultados = Efectivo.query.filter(
                (Efectivo.fullname.like(f'%{query}%')) |
                (Efectivo.DNI.like(f'%{query}%')) |
                (Efectivo.LP.like(f'%{query}%'))
            ).all()

        elif tabla == 'expediente':
            resultados = Expte.query.filter(
                (Expte.proc.like(f'%{query}%')) |
                (Expte.detalle.like(f'%{query}%')) |
                (Expte.secretario.like(f'%{query}%')) |
                (Expte.instructor.like(f'%{query}%'))
            ).all()

        elif tabla == 'causa':
            resultados = Causa.query.filter(
                (Causa.ptvo.like(f'%{query}%')) |
                (Causa.detalle.like(f'%{query}%')) |
                (Causa.nroExpte.like(f'%{query}%')) |
                (Causa.secretario.like(f'%{query}%')) |
                (Causa.instructor.like(f'%{query}%'))
            ).all()

        elif tabla == 'todos':
            resultados_efectivo = Efectivo.query.filter(
                (Efectivo.fullname.like(f'%{query}%')) |
                (Efectivo.DNI.like(f'%{query}%')) |
                (Efectivo.LP.like(f'%{query}%'))
            ).all()

            resultados_expediente = Expte.query.filter(
                (Expte.proc.like(f'%{query}%')) |
                (Expte.detalle.like(f'%{query}%')) |
                (Expte.secretario.like(f'%{query}%')) |
                (Expte.instructor.like(f'%{query}%'))
            ).all()

            resultados_causa = Causa.query.filter(
                (Causa.ptvo.like(f'%{query}%')) |
                (Causa.detalle.like(f'%{query}%')) |
                (Causa.nroExpte.like(f'%{query}%')) |
                (Causa.secretario.like(f'%{query}%')) |
                (Causa.instructor.like(f'%{query}%'))
            ).all()

            resultados = resultados_efectivo + resultados_expediente + resultados_causa

    return render_template('resultados.html', resultados=resultados)


@causas.route('/about')
def about():
    return render_template('about.html')

routes/NrosJ.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, send_file
from models.NroJ import nroJ
from utils import db
from utils.db import db
from datetime import datetime
import pandas as pd
from io import BytesIO
from flask_login import login_required

#Uso de blueprint, sirve para no tener que importar app y cargar los metodos y los html aca
NrosJ = Blueprint('NrosJ', __name__)

@NrosJ.route('/NrosJ')
@login_required
def home():
    NrosJ = nroJ.query.all()
    return render_template('NumerosJudiciales.html', NrosJ=NrosJ)


@NrosJ.route('/new_NroJ', methods=['POST'])
def add_NroJ():
    fecha=datetime.strptime(request.form['fecha'], '%Y-%m-%d')
    secretario=request.form['secretario']
    destino=request.form['destino']
    motivo=request.form['motivo']
    

    new_NroJ = nroJ(fecha, secretario, destino, motivo)
    
    db.session.add(new_NroJ)
    db.session.commit()


    flash("Se ha marcó un numero judicial satisfactoriamente!")

    return redirect(url_for('NrosJ.home'))

@NrosJ.route('/NrosJ/update/<id>', methods=['POST', 'GET'])
def update(id):
        print(id)
        NroJ = nroJ.query.get(id)
        if request.method == 'POST':
            
            NroJ.fecha = request.form["fecha"]
            NroJ.secretario = request.form["secretario"]
            NroJ.destino = request.form["destino"]
            NroJ.motivo = request.form["motivo"]

            db.session.commit()
            
            flash("Se actualizó un numero judicial satisfactoriamente!")

            return redirect(url_for('NrosJ.home')) 
        
        
        return render_template('updateNroJ.html', NroJ=NroJ)

@NrosJ.route('/NrosJ/delete/<id>')
def delete(id):
        NroJ = nroJ.query.get(id)
        db.session.delete(NroJ)
        db.session.commit()

        flash("Se borró un Numero judicial satisfactoriamente!")


        return redirect(url_for('NrosJ.home'))

@NrosJ.route('/export/NrosJ')
def export_excel():
    # Consulta de los datos de la base de datos
    NrosJ = nroJ.query.all()
    
    # Crear un DataFrame de Pandas
    data = [
        {
            "ID": NroJ.id,
            "Fecha": NroJ.fecha,
            "Secretario": NroJ.secretario,
            "Destino": NroJ.destino,
            "Motivo": NroJ.motivo,

        }
        for NroJ in NrosJ
    ]
    df = pd.DataFrame(data)

    # Guardar el DataFrame en un archivo Excel en memoria
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name="NrosJ")
    output.seek(0)

    # Enviar el archivo al cliente para descargarlo
    return send_file(output, as_attachment=True, download_name="NrosJ.xlsx", mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")




@NrosJ.route('/about')
def about():
    return render_template('about.html')

routes/exptes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, send_file
from models.expte import Expte
from models.Causa import Causa
from models.efectivo import Efectivo
from utils import db
from utils.db import db
from datetime import datetime
import pandas as pd
from io import BytesIO
from flask_login import login_required

#Uso de blueprint, sirve para no tener que importar app y cargar los metodos y los html aca
exptes = Blueprint('exptes', __name__)

@exptes.route('/exptes')
@login_required
def home():
    exptes = Expte.query.all()
    return render_template('expedientes.html', exptes=exptes)


@exptes.route('/new_expte', methods=['POST'])
def add_expte():
    fechaing=datetime.strptime(request.form['fechaing'], '%Y-%m-%d')
    proc=request.form['proc']
    detalle=request.form['detalle']
    secretario=request.form['secretario']
    instructor=request.form['instructor']
    destino=request.form['destino']
    fechasal=request.form['fechasal']
    if fechasal:
        fechasal = datetime.strptime(fechasal, '%Y-%m-%d')
    else:
        fechasal = None
    obs=request.form['obs']
    

    new_expte = Expte(fechaing, proc, detalle, secretario, instructor, destino, fechasal, obs)
    
    db.session.add(new_expte)
    db.session.commit()


    flash("Se ha añadido un expediente satisfactoriamente!")

    return redirect(url_for('exptes.home'))

@exptes.route('/exptes/update/<id>', methods=['POST', 'GET'])
def update(id):
        print(id)
        expte = Expte.query.get(id)
        if request.method == 'POST':
            
            expte.fechaing = request.form["fechaing"]
            expte.proc = request.form["proc"]
            expte.detalle = request.form["detalle"]
            expte.secretario = request.form["secretario"]
            expte.instructor = request.form["instructor"]
            expte.destino = request.form["destino"]
            expte.fechasal = request.form["fechasal"]
            expte.obs = request.form["obs"]

            db.session.commit()
            
            flash("Se actualizó un expediente satisfactoriamente!")

            return redirect(url_for('exptes.home')) 
        
        
        return render_template('updateexpte.html', expte=expte)

@exptes.route('/exptes/delete/<id>')
def delete(id):
        expte = Expte.query.get(id)
        db.session.delete(expte)
        db.session.commit()

        flash("Se borró un expediente satisfactoriamente!")


        return redirect(url_for('exptes.home'))

@exptes.route('/export/exptes')
def export_excel():
    # Consulta de los datos de la base de datos
    exptes = Expte.query.all()
    
    # Crear un DataFrame de Pandas
    data = [
        {
            "ID": expte.id,
            "Fecha Ingreso": expte.fechaing,
            "Procedencia": expte.proc,
            "Detalle": expte.detalle,
            "Secretario": expte.secretario,
            "Instructor": expte.instructor,
            "Destino": expte.destino,
            "Fecha Salida": expte.fechasal,
            "Observaciones": expte.obs,

        }
        for expte in exptes
    ]
    df = pd.DataFrame(data)

    # Guardar el DataFrame en un archivo Excel en memoria
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name="exptes")
    output.seek(0)

    # Enviar el archivo al cliente para descargarlo
    return send_file(output, as_attachment=True, download_name="exptes.xlsx", mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")

@exptes.route('/buscar', methods=['GET'])
def buscar():
    query = request.args.get('query')
    tabla = request.args.get('tabla')
    resultados = []

    if query:
        if tabla == 'efectivo':
            resultados = Efectivo.query.filter(
                (Efectivo.fullname.like(f'%{query}%')) |
                (Efectivo.DNI.like(f'%{query}%')) |
                (Efectivo.LP.like(f'%{query}%'))
            ).all()

        elif tabla == 'expediente':
            resultados = Expte.query.filter(
                (Expte.proc.like(f'%{query}%')) |
                (Expte.detalle.like(f'%{query}%')) |
                (Expte.secretario.like(f'%{query}%')) |
                (Expte.instructor.like(f'%{query}%'))
            ).all()

        elif tabla == 'causa':
            resultados = Causa.query.filter(
                (Causa.ptvo.like(f'%{query}%')) |
                (Causa.detalle.like(f'%{query}%')) |
                (Causa.nroExpte.like(f'%{query}%')) |
                (Causa.secretario.like(f'%{query}%')) |
                (Causa.instructor.like(f'%{query}%'))
            ).all()

        elif tabla == 'todos':
            resultados_efectivo = Efectivo.query.filter(
                (Efectivo.fullname.like(f'%{query}%')) |
                (Efectivo.DNI.like(f'%{query}%')) |
                (Efectivo.LP.like(f'%{query}%'))
            ).all()

            resultados_expediente = Expte.query.filter(
                (Expte.proc.like(f'%{query}%')) |
                (Expte.detalle.like(f'%{query}%')) |
                (Expte.secretario.like(f'%{query}%')) |
                (Expte.instructor.like(f'%{query}%'))
            ).all()

            resultados_causa = Causa.query.filter(
                (Causa.ptvo.like(f'%{query}%')) |
                (Causa.detalle.like(f'%{query}%')) |
                (Causa.nroExpte.like(f'%{query}%')) |
                (Causa.secretario.like(f'%{query}%')) |
                (Causa.instructor.like(f'%{query}%'))
            ).all()

            resultados = resultados_efectivo + resultados_expediente + resultados_causa

    return render_template('resultados.html', resultados=resultados)


@exptes.route('/about')
def about():
    return render_template('about.html')

routes/secuestros.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, send_file
from models.secuestro import Secuestro
from utils import db
from utils.db import db
from datetime import datetime
import pandas as pd
from io import BytesIO
from flask_login import login_required

#Uso de blueprint, sirve para no tener que importar app y cargar los metodos y los html aca
secuestros = Blueprint('secuestros', __name__)

@secuestros.route('/secuestros')
@login_required
def home():
    secuestros = Secuestro.query.all()
    return render_template('Secuestros.html', secuestros=secuestros)


@secuestros.route('/new_secuestro', methods=['POST'])
def add_secuestro():
    fechaing=datetime.strptime(request.form['fechaing'], '%Y-%m-%d')
    detalle=request.form['detalle']
    nroExpte=request.form['nroExpte']
    fechasal=request.form['fechasal']


    

    new_secuestro = Secuestro(fechaing, detalle, nroExpte, fechasal,)
    
    db.session.add(new_secuestro)
    db.session.commit()


    flash("Se ha añadido una secuestro satisfactoriamente!")

    return redirect(url_for('secuestros.home'))

@secuestros.route('/secuestros/update/<id>', methods=['POST', 'GET'])
def update(id):
        print(id)
        secuestro = Secuestro.query.get(id)
        if request.method == 'POST':
            
            secuestro.fechaing = request.form["fechaing"]
            secuestro.detalle = request.form["detalle"]
            secuestro.nroExpte = request.form["nroExpte"]
            secuestro.fechasal = request.form["fechasal"]



            db.session.commit()
            
            flash("Se actualizó una secuestro satisfactoriamente!")

            return redirect(url_for('secuestros.home')) 
        
        
        return render_template('updatesecuestros.html', secuestro=secuestro)

@secuestros.route('/secuestros/delete/<id>')
def delete(id):
        secuestro = Secuestro.query.get(id)
        db.session.delete(secuestro)
        db.session.commit()

        flash("Se borró una secuestro satisfactoriamente!")


        return redirect(url_for('secuestros.home'))

@secuestros.route('/export/secuestros')
def export_excel():
    # Consulta de los datos de la base de datos
    secuestros = Secuestro.query.all()
    
    # Crear un DataFrame de Pandas
    data = [
        {
            "ID": secuestro.id,
            "Fecha Ingreso": secuestro.fechaing,
            "Detalle": secuestro.detalle,
            "Nro. Expte": secuestro.nroExpte,
            "Fecha Salida": secuestro.fechasal,

        }
        for secuestro in secuestros
    ]
    df = pd.DataFrame(data)

    # Guardar el DataFrame en un archivo Excel en memoria
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name="secuestros")
    output.seek(0)

    # Enviar el archivo al cliente para descargarlo
    return send_file(output, as_attachment=True, download_name="secuestros.xlsx", mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")



@secuestros.route('/about')
def about():
    return render_template('about.html')

templates/NumerosJudiciales.html
{% extends 'layout.html' %}

{% block title %}
  CRUD Carga de personal | Home 
{% endblock %}

{% block body %}

    <!-- FORM -->
    <div class="row">
    
    <div class="col-md-5 p-5">
      <!-- MESSAGE -->
      {% include 'partials/_message.html' %}
  
      <!-- FORM -->
      {%  include 'partials/_NroJForm.html' %}
    </div>
    <!--  listado de expedientes -->
    <div class="col-md-7">
      {% for NroJ in NrosJ %}
        <div class="card mb-1 bg-black text-white">
          <div class="card-body py-2 px-3">
            <div class="d-flex justify-content-between">
              <h5 class="card-title h6"> Numero N° {{ NroJ.id }}</h5>
              <div>
                <a href="{{ url_for('NrosJ.update', id=NroJ.id) }}" class="btn btn-dark btn-sm rounded-0">Edit</a>
                <a href="{{ url_for('NrosJ.delete', id=NroJ.id) }}" class="btn btn-danger btn-sm rounded-0">Delete</a>
              </div>
            </div>
            <p class="card-text">Fecha: {{ NroJ.fecha }}</p>
            <p class="card-text">Secretario: {{ NroJ.secretario }}</p>
            <p class="card-text">Destino: {{ NroJ.destino }}</p>
            <p class="card-text">Motivo: {{ NroJ.motivo }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
  

  </div>
    </div>





{% endblock %}

templates/NumerosVarios.html
{% extends 'layout.html' %}

{% block title %}
  CRUD Carga de personal | Home 
{% endblock %}

{% block body %}

    <!-- FORM -->
    <div class="row">
    
    <div class="col-md-5 p-5">
      <!-- MESSAGE -->
      {% include 'partials/_message.html' %}
  
      <!-- FORM -->
      {%  include 'partials/_NroVarioForm.html' %}
    </div>
    <!--  listado de expedientes -->
    <div class="col-md-7">
      {% for NroV in NrosV %}
        <div class="card mb-1 bg-black text-white">
          <div class="card-body py-2 px-3">
            <div class="d-flex justify-content-between">
              <h5 class="card-title h6"> Numero N° {{ NroV.id }}</h5>
              <div>
                <a href="{{ url_for('NrosV.update', id=NroV.id) }}" class="btn btn-dark btn-sm rounded-0">Edit</a>
                <a href="{{ url_for('NrosV.delete', id=NroV.id) }}" class="btn btn-danger btn-sm rounded-0">Delete</a>
              </div>
            </div>
            <p class="card-text">Fecha: {{ NroV.fecha }}</p>
            <p class="card-text">Secretario: {{ NroV.secretario }}</p>
            <p class="card-text">Destino: {{ NroV.destino }}</p>
            <p class="card-text">Motivo: {{ NroV.motivo }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
  

  </div>
    </div>





{% endblock %}

templates/UpdateCausas.html
{% extends "layout.html" %} {% block body %}

<div class="col-md-4 offset-md-4">
  <div class="card card-body bg-dark text-white">
    <h1>Edit Task</h1>

    <form action="{{url_for('causas.update', id=causa.id)}}" method="POST">

        <div class="mb-3">
        <label for="fechaini">Fecha inicio:</label>
        <input
          type="date"
          name="fechaini"
          value="{{causa.fechaini}}"
          class="form-control bg-dark text-white rounded-0"
        />
        </div>

      <div class="mb-3">
        <label for="ptvo">Preventivo:</label>
        <input
          type="text"
          name="ptvo"
          value="{{causa.ptvo}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>
      <div class="mb-3">
        <label for="nroExpte">Numero Expediente:</label>
        <input
          type="text"
          name="nroExpte"
          value="{{causa.nroExpte}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>

      <div class="mb-3">
        <label for="detalle">Detalle:</label>
        <input
          type="text"
          name="detalle"
          value="{{causa.detalle}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>

      <div class="mb-3">
        <label for="secretario">ID del secretario:</label>
        <input
          type="number"
          name="secretario"
          value="{{causa.secretario}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>

      <div class="mb-3">
        <label for="instructor">ID del instructor:</label>
        <input
          type="number"
          name="instructor"
          value="{{causa.instructor}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>

      <button class="btn btn-primary">Update</button>
    </form>
  </div>
</div>

{% endblock %}

templates/UpdateSecuestro.html
{% extends "layout.html" %} {% block body %}

<div class="col-md-4 offset-md-4">
  <div class="card card-body bg-dark text-white">
    <h1>Edit Task</h1>

    <form action="{{url_for('secuestros.update', id=secuestro.id)}}" method="POST">

        <div class="mb-3">
        <label for="fechaing">Fecha ingreso:</label>
        <input
          type="date"
          name="fechaing"
          value="{{secuestro.fechaing}}"
          class="form-control bg-dark text-white rounded-0"
        />
        </div>

        <div class="mb-3">
            <label for="detalle">Detalle:</label>
            <input
              type="text"
              name="detalle"
              value="{{secuestro.detalle}}"
              class="form-control bg-dark text-white rounded-0"
            />
        </div>

      <div class="mb-3">
        <label for="nroExpte">Numero Expediente:</label>
        <input
          type="text"
          name="nroExpte"
          value="{{secuestro.nroExpte}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>

      <div class="mb-3">
        <label for="fechasal">Fecha de Salida:</label>
        <input
          type="number"
          name="fechasal"
          value="{{secuestro.fechasal}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>

      <button class="btn btn-primary">Update</button>
    </form>
  </div>
</div>

{% endblock %}

templates/expedientes.html
{% extends 'layout.html' %}

{% block title %}
  CRUD Carga de personal | Home 
{% endblock %}

{% block body %}

    <!-- FORM -->
    <div class="row">
    <form action="/buscar" method="GET" class="mb-4">
        <div class="mb-3">
          <input type="text" name="query" class="form-control" placeholder="Buscar por nombre, DNI o legajo" required>
        </div>
        <div class="mb-3">
          <label for="tabla">Buscar en:</label>
          <select name="tabla" class="form-select">
              <option value="todos">Todas las tablas</option>
              <option value="efectivo">Efectivos</option>
              <option value="expediente">Expedientes</option>
              <option value="causa">Causas</option>
          </select>
      </div>
        <button type="submit" class="btn btn-primary mt-2">Buscar</button>
    </form>  
    
    <div class="col-md-5 p-5">
      <!-- MESSAGE -->
      {% include 'partials/_message.html' %}
  
      <!-- FORM -->
      {%  include 'partials/_expteForm.html' %}
    </div>
    <!--  listado de expedientes -->
    <div class="col-md-7">
      {% for expte in exptes %}
        <div class="card mb-1 bg-black text-white">
          <div class="card-body py-2 px-3">
            <div class="d-flex justify-content-between">
              <h5 class="card-title h6"> Expte. N° {{ expte.id }}</h5>
              <div>
                <a href="{{ url_for('exptes.update', id=expte.id) }}" class="btn btn-dark btn-sm rounded-0">Edit</a>
                <a href="{{ url_for('exptes.delete', id=expte.id) }}" class="btn btn-danger btn-sm rounded-0">Delete</a>
              </div>
            </div>
            <p class="card-text">Fecha Ingreso: {{ expte.fechaing }}</p>
            <p class="card-text">Procedencia: {{ expte.proc }}</p>
            <p class="card-text">Detalle: {{ expte.detalle }}</p>
            <p class="card-text">Instructor: {{ expte.instructor }}</p>
            <p class="card-text">Secretario: {{ expte.secretario }}</p>
            <p class="card-text">Destino: {{ expte.destino }}</p>
            <p class="card-text">Fecha Salida: {{ expte.fechasal }}</p>
            <p class="card-text">Observaciones{{ expte.obs }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
  

  </div>
    </div>





{% endblock %}

templates/login.html
{% extends "layout.html" %}

{% block title %}
  Login | RegPol
{% endblock %}

{% block body %}
  <div class="container mt-5">
    <!-- Incluir el partial de mensajes -->
    {% include 'partials/_message.html' %}

    <!-- Formulario de login -->
    <form method="POST" action="{{ url_for('users.login') }}">
      <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" id="username" name="username" required>
      </div>
      <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password" required>
      </div>
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
  </div>
{% endblock %}

templates/updateNroJ.html
{% extends "layout.html" %} {% block body %}

<div class="col-md-4 offset-md-4">
  <div class="card card-body bg-dark text-white">
    <h1>Edit Task</h1>

    <form action="{{url_for('NrosJ.update', id=NroJ.id)}}" method="POST">

        <div class="mb-3">
        <label for="fechaing">Fecha:</label>
        <input
          type="date"
          name="fecha"
          value="{{NroJ.fecha}}"
          class="form-control bg-dark text-white rounded-0"
        />
        </div>

      <div class="mb-3">
        <label for="secretario">LP del secretario:</label>
        <input
          type="number"
          name="secretario"
          value="{{NroJ.secretario}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>


      <div class="mb-3">
        <label for="destino">Destino:</label>
        <input
          type="text"
          name="destino"
          value="{{NroJ.destino}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>


      <div class="mb-3">
        <label for="motivo">Motivo:</label>
        <input
          type="text"
          name="motivo"
          value="{{NroJ.motivo}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>


      <button class="btn btn-primary">Update</button>
    </form>
  </div>
</div>

{% endblock %}